[build]
builder = "NIXPACKS"
buildCommand = "cd webapp/react-app && npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "python run_webapp.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "5000"
